import random
import string

ram = string.ascii_lowercase
cat1 = random.choice(ram)
cat2 = random.choice(ram)
cat3 = random.choice(ram)
cat4 = random.choice(ram)
cat5 = random.choice(ram)
cat6 = random.choice(ram)
cat7 = random.choice(ram)
cat8 = random.choice(ram)
cat9 = random.choice(ram)
cat10 = random.choice(ram)
cat11 = random.choice(ram)
cat12 = random.choice(ram)
cat13 = random.choice(ram)
cat14 = random.choice(ram)
cat15 = random.choice(ram)
cat16 = random.choice(ram)
cat17 = random.choice(ram)
cat18 = random.choice(ram)


dog1 = (random.randint(0, 9))
dog2 = (random.randint(0, 9))
dog3 = (random.randint(0, 9))
dog4 = (random.randint(0, 9))
dog5 = (random.randint(0, 9))
dog6 = (random.randint(0, 9))
dog7 = (random.randint(0, 9))
dog8 = (random.randint(0, 9))
dog9 = (random.randint(0, 9))
dog10 = (random.randint(0, 9))
dog11 = (random.randint(0, 9))
dog12 = (random.randint(0, 9))
dog13 = (random.randint(0, 9))
dog14 = (random.randint(0, 9))
dog15 = (random.randint(0, 9))
dog16 = (random.randint(0, 9))
dog17 = (random.randint(0, 9))
dog18 = (random.randint(0, 9))
dog19 = (random.randint(0, 9))
dog20 = (random.randint(0, 9))
dog21 = (random.randint(0, 9))
dog22 = (random.randint(0, 9))
dog23 = (random.randint(0, 9))
dog24 = (random.randint(0, 9))

print ("Hacking ...",cat1,cat2,cat3,dog1,dog2,dog3,cat4,cat5,cat6,dog4,dog5,dog6,cat7,cat8,cat9)
